# Generated by Django 3.1.7 on 2021-03-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egyNationalId', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalID',
        ),
    ]
