# Generated by Django 3.1.7 on 2021-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyNationalId', '0004_remove_nationalid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalid',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
